[package]
name    = "spacesim-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "spacesim-cli"
path = "src/main.rs"

[dependencies]
spacesim-core  = { path = "../core" }
spacesim-types = { path = "../types" }
anyhow         = { workspace = true }
tracing        = { workspace = true }
tracing-subscriber = { workspace = true }
