[package]
name    = "spacesim-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
spacesim-types = { path = "../types" }
serde          = { workspace = true }
serde_json     = { workspace = true }
tokio          = { workspace = true }
rmp-serde      = { workspace = true }
anyhow         = { workspace = true }
tracing        = { workspace = true }
